/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Objeto.VentanaPrincipal;

import Objeto.Paneles.Cotizacion;
import Objetos.IngresoUsuarios;
import Objetos.Kioskos;

import Objeto.Paneles.Guia;
import Objeto.Paneles.IngresoKiosko;
import Objeto.Paneles.MostrarKioskos;
import Objeto.Paneles.Pago;
import static Objeto.Paneles.Pago.generarCadena;
import static Objeto.Paneles.Pago.generarCadenaAleatoria;
import Objeto.Paneles.PanelUsuario;
import Objeto.Paneles.PrincipalAdmin;
import Objeto.Paneles.RegistoTarjeta;
import Objeto.Paneles.RegistroDatosFacturacion;
import Objeto.Paneles.RegistroUsuarios;
import Objeto.Paneles.ReporteAdmin;
import Objeto.Paneles.login;
import Objetos.datoFactura;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import java.awt.*;
import java.awt.print.*;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.util.Random;
import java.time.LocalDate;
import javax.swing.JOptionPane;


public class VentanaPrincipal extends javax.swing.JFrame implements Printable{

    
    public VentanaPrincipal() {
        initComponents();
        cambiarpaneles(login);
        this.setTitle("USAC-Delivery_202200110_Evelyn Balcarcel");
        PBinicio.setVisible(true);
        PBadmin.setVisible(false);
       // Pusuariocliente.setVisible(false);
        PBkiosko.setVisible(false);
        setLocationRelativeTo(null);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        Blogin = new javax.swing.JButton();
        mensajedesesion = new javax.swing.JLabel();
        PBinicio = new javax.swing.JPanel();
        Bcrearusuario = new javax.swing.JButton();
        Biniciarsesion = new javax.swing.JButton();
        PBadmin = new javax.swing.JPanel();
        entrarKiosko = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        PBkiosko = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        Bmostarkiosko = new javax.swing.JButton();
        BagregarAkiosko = new javax.swing.JButton();
        bgeneralU = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        subPanel = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        seguirB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        PanelPrincipal.setBackground(new java.awt.Color(0, 0, 0));
        PanelPrincipal.setPreferredSize(new java.awt.Dimension(400, 300));

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        Blogin.setBackground(new java.awt.Color(0, 0, 0));
        Blogin.setForeground(new java.awt.Color(204, 0, 0));
        Blogin.setText("Inicio");
        Blogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BloginActionPerformed(evt);
            }
        });

        mensajedesesion.setText("....");

        PBinicio.setBackground(new java.awt.Color(0, 0, 0));
        PBinicio.setForeground(new java.awt.Color(0, 0, 0));

        Bcrearusuario.setBackground(new java.awt.Color(255, 255, 255));
        Bcrearusuario.setForeground(new java.awt.Color(0, 0, 0));
        Bcrearusuario.setText("Agregar usuarios");
        Bcrearusuario.setActionCommand("Agregar usuarios");
        Bcrearusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcrearusuarioActionPerformed(evt);
            }
        });

        Biniciarsesion.setBackground(new java.awt.Color(255, 255, 255));
        Biniciarsesion.setForeground(new java.awt.Color(0, 0, 0));
        Biniciarsesion.setText("Iniciar Sesion");
        Biniciarsesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BiniciarsesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PBinicioLayout = new javax.swing.GroupLayout(PBinicio);
        PBinicio.setLayout(PBinicioLayout);
        PBinicioLayout.setHorizontalGroup(
            PBinicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PBinicioLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(PBinicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Bcrearusuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Biniciarsesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PBinicioLayout.setVerticalGroup(
            PBinicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PBinicioLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(Biniciarsesion)
                .addGap(18, 18, 18)
                .addComponent(Bcrearusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        PBadmin.setBackground(new java.awt.Color(0, 0, 0));
        PBadmin.setForeground(new java.awt.Color(0, 0, 0));

        entrarKiosko.setBackground(new java.awt.Color(255, 255, 255));
        entrarKiosko.setForeground(new java.awt.Color(0, 0, 0));
        entrarKiosko.setText("Manejo de Kioskos");
        entrarKiosko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarKioskoActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Ver Reportes");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(255, 255, 255));
        jButton10.setForeground(new java.awt.Color(0, 0, 0));
        jButton10.setText("Agregar Usuario/Cliente");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PBadminLayout = new javax.swing.GroupLayout(PBadmin);
        PBadmin.setLayout(PBadminLayout);
        PBadminLayout.setHorizontalGroup(
            PBadminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PBadminLayout.createSequentialGroup()
                .addGroup(PBadminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PBadminLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jButton3))
                    .addGroup(PBadminLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton10))
                    .addGroup(PBadminLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(entrarKiosko)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PBadminLayout.setVerticalGroup(
            PBadminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PBadminLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jButton10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(entrarKiosko)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        PBkiosko.setBackground(new java.awt.Color(0, 0, 0));
        PBkiosko.setForeground(new java.awt.Color(0, 0, 0));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("Regresar al administrador");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        Bmostarkiosko.setBackground(new java.awt.Color(255, 255, 255));
        Bmostarkiosko.setForeground(new java.awt.Color(0, 0, 0));
        Bmostarkiosko.setText("Mostar Kioskos");
        Bmostarkiosko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BmostarkioskoActionPerformed(evt);
            }
        });

        BagregarAkiosko.setBackground(new java.awt.Color(255, 255, 255));
        BagregarAkiosko.setForeground(new java.awt.Color(0, 0, 0));
        BagregarAkiosko.setText("Seguir agregando kioskos");
        BagregarAkiosko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BagregarAkioskoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PBkioskoLayout = new javax.swing.GroupLayout(PBkiosko);
        PBkiosko.setLayout(PBkioskoLayout);
        PBkioskoLayout.setHorizontalGroup(
            PBkioskoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PBkioskoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PBkioskoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BagregarAkiosko)
                    .addGroup(PBkioskoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(Bmostarkiosko, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        PBkioskoLayout.setVerticalGroup(
            PBkioskoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PBkioskoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Bmostarkiosko)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BagregarAkiosko)
                .addGap(22, 22, 22))
        );

        bgeneralU.setBackground(new java.awt.Color(0, 0, 0));

        jButton9.setBackground(new java.awt.Color(255, 255, 255));
        jButton9.setForeground(new java.awt.Color(0, 0, 0));
        jButton9.setText("Pago");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setForeground(new java.awt.Color(0, 0, 0));
        jButton5.setText("Cotizacion");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Registro de Facturacion");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Registrar Tarjeta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        subPanel.setBackground(new java.awt.Color(0, 0, 0));

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setForeground(new java.awt.Color(0, 0, 0));
        jButton7.setText("Guia");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setForeground(new java.awt.Color(0, 0, 0));
        jButton6.setText("Factura ");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimirfactura(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(255, 255, 255));
        jButton11.setForeground(new java.awt.Color(0, 0, 0));
        jButton11.setText("Confirmar pago y enviar");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout subPanelLayout = new javax.swing.GroupLayout(subPanel);
        subPanel.setLayout(subPanelLayout);
        subPanelLayout.setHorizontalGroup(
            subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subPanelLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton11)
                    .addGroup(subPanelLayout.createSequentialGroup()
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                .addGap(26, 26, 26))
        );
        subPanelLayout.setVerticalGroup(
            subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jButton11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addContainerGap())
        );

        seguirB.setBackground(new java.awt.Color(255, 255, 255));
        seguirB.setForeground(new java.awt.Color(0, 0, 0));
        seguirB.setText("Quiero un nuevo envio");
        seguirB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seguirBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgeneralULayout = new javax.swing.GroupLayout(bgeneralU);
        bgeneralU.setLayout(bgeneralULayout);
        bgeneralULayout.setHorizontalGroup(
            bgeneralULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgeneralULayout.createSequentialGroup()
                .addGroup(bgeneralULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgeneralULayout.createSequentialGroup()
                        .addGroup(bgeneralULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(bgeneralULayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bgeneralULayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bgeneralULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(bgeneralULayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(seguirB)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(subPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        bgeneralULayout.setVerticalGroup(
            bgeneralULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgeneralULayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(bgeneralULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(subPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bgeneralULayout.createSequentialGroup()
                        .addGroup(bgeneralULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(bgeneralULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5)
                            .addComponent(jButton9))
                        .addGap(18, 18, 18)
                        .addComponent(seguirB)))
                .addGap(114, 114, 114))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Blogin)
                        .addGap(18, 18, 18)
                        .addComponent(mensajedesesion, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(bgeneralU, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PanelPrincipal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PBadmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PBkiosko, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PBinicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(453, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mensajedesesion)
                    .addComponent(Blogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PBinicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(PBadmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(PBkiosko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(bgeneralU, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BloginActionPerformed
        PBinicio.setVisible(true);
        cambiarpaneles(login);
        PBkiosko.setVisible(false);
        PBadmin.setVisible(false);
       // Pusuariocliente.setVisible(false);

    }//GEN-LAST:event_BloginActionPerformed

    private void BcrearusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcrearusuarioActionPerformed
        // TODO add your handling code here:
        //PregistroU.combok.setEnabled(false);
        mensajedesesion.setText("");
       
        for (int i = 0; i < Ikiosko.getListakiosko().size(); i++) {
           //PregistroU.combok.addItem(Ikiosko.getListakiosko().get(i).getNombrekiosko().toString()); 
        }
        cambiarpaneles(PregistroU);
        PBinicio.setVisible(false);

    }//GEN-LAST:event_BcrearusuarioActionPerformed

    private void BiniciarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BiniciarsesionActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < PregistroU.getlistausuarios().size(); i++) {
            IngresoUsuarios temporal = new IngresoUsuarios();
            temporal = PregistroU.getlistausuarios().get(i);

            if (login.getClave().equals("202200110") && login.getUsuario().equals("ipc1_202200110@ipc1delivery.com")) {
                cambiarpaneles(Padmin);
                //ipc1_20220o110@ipc1delivery.com
                PBinicio.setVisible(false);
                PBadmin.setVisible(true);
                mensajedesesion.setVisible(false);
            } else if (login.getClave().equals(temporal.getContraseña()) && login.getUsuario().equals(temporal.getCorreo())) {             
                //Ikiosko variable registro de kisokos
                //PregistroU variable de registro usuarios 
                
                
                
                cambiarpaneles(panelU);//cambiar Padmin por panel de usuario
                seguirB.setVisible(false);
                subPanel.setVisible(false);
                PBinicio.setVisible(false);
                PBadmin.setVisible(true);
                mensajedesesion.setVisible(false);
                Pusuariocliente.setVisible(true);
                PBadmin.setVisible(false);
            }
            else{mensajedesesion.setText("Usuario o contraseña invalida");}
        }
    }//GEN-LAST:event_BiniciarsesionActionPerformed

    final String cadena = "ABCDEFGHIJKLMNOPQRSTUVWZYabcdefghijklmnopqrstuvwxyz0123456789";
    final int longitud = 10;
    StringBuilder sb = new StringBuilder();

    private void entrarKioskoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarKioskoActionPerformed
        // TODO add your handling code here: 
        /* Ikiosko.cambiarcodigo("");
    Ikiosko.revalidate();
    Ikiosko.repaint();    
    for(int i=0;i<longitud;i++){
    double aleatorio=Math.random()*cadena.length();
    int posicion=(int)aleatorio;
    char letra=cadena.charAt(posicion);
    sb.append(letra);}
   
    String Caleatorio = sb.toString();
    Ikiosko.cambiarcodigo(Caleatorio);         */

        PBkiosko.setVisible(true);
        PBadmin.setVisible(false);
        cambiarpaneles(Ikiosko);
    }//GEN-LAST:event_entrarKioskoActionPerformed
double tot=0;
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
  
        String temp11=pago.totalFacturar.getText();
        double temp22=Cot.getOperacion();
        double convertTemp11=Double.parseDouble(temp11);
        tot=tot+temp22+convertTemp11;
        
        cambiarpaneles(repAdmin);
        repAdmin.paqR.setText(String.valueOf(paquetesR));
        repAdmin.toR.setText(String.valueOf(tot));
        
        DefaultTableModel modelito = (DefaultTableModel) repAdmin.tablitaRegiones.getModel();
        modelito.setValueAt( M, 0, 0);
        modelito.setValueAt( NT, 0, 1);
        modelito.setValueAt( NO, 0, 2);
        modelito.setValueAt( SO, 0, 3);
        modelito.setValueAt( SOC, 0, 4);
        modelito.setValueAt( NOC, 0, 5);
        
        repAdmin.tablitaRegiones.getTableHeader().repaint();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        PBadmin.setVisible(true);
        PBkiosko.setVisible(false);
        cambiarpaneles(Padmin);
    }//GEN-LAST:event_jButton4ActionPerformed

    IngresoKiosko InK = new IngresoKiosko();


    private void BmostarkioskoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BmostarkioskoActionPerformed
        // TODO add your handling code here:
        String textokiosko = "";

        for (int i = 0; i < InK.getListakiosko().size(); i++) {
            Kioskos temporal = new Kioskos();
            temporal = InK.getListakiosko().get(i);
            textokiosko = textokiosko + "Codigo: " + temporal.getCodigokiosko() + " Nombre: " + temporal.getNombrekiosko() + " Region: " + temporal.getCodigoderegion() + '\n';
            System.out.println("Codigo: " + temporal.getCodigokiosko() + " Nombre: " + temporal.getNombrekiosko() + " Region: " + temporal.getCodigoderegion());
        }

        MK.setTextArea(textokiosko);//MK porque viene de Mostrar Kioskos, tiene un metodo void que tiene decladrado donde se guarda
        cambiarpaneles(MK); //aqui cambia el panel y muestra todo lo hecho o guardado en el panel de Mostrar kiosko 
        BagregarAkiosko.setVisible(true);
    }//GEN-LAST:event_BmostarkioskoActionPerformed

    private void BagregarAkioskoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BagregarAkioskoActionPerformed
        // TODO add your handling code here:
        cambiarpaneles(InK);
        BagregarAkiosko.setVisible(false);

    }//GEN-LAST:event_BagregarAkioskoActionPerformed

 
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        //no se debe de tocar nada 
        subPanel.setVisible(true);
        jButton11.setVisible(true);
        subPanel.setEnabled(true);
        pago.setlistTarjeta(RegT.getListaTarjeta());
        pago.MandarDatosListaDesplegable();
        cambiarpaneles(pago); 
        
        
        //hasta aqui no se debe tocar nada
     pago.tablaD2.removeAll();
     DefaultTableModel modelo2 = (DefaultTableModel) pago.tablaD2.getModel();
     
     TableColumn columna11 = pago.tablaD2.getColumnModel().getColumn(0);
     columna11.setHeaderValue("Tipo de Servicio");
     
     TableColumn columna22 = pago.tablaD2.getColumnModel().getColumn(1);
     columna22.setHeaderValue("Total en Q");
     
     modelo2.setValueAt( Cot.getTipoServicio(), 0, 0);
    modelo2.setValueAt( Cot.getTotal(), 0, 1);
        //llenado de la tabla de datos de Factura
     pago.tablaFact.removeAll();
     DefaultTableModel modelo = (DefaultTableModel) pago.tablaFact.getModel();
     
     TableColumn columna1 = pago.tablaFact.getColumnModel().getColumn(0);
     columna1.setHeaderValue("Nombre");
     
     TableColumn columna2 = pago.tablaFact.getColumnModel().getColumn(1);
     columna2.setHeaderValue("Direccion");
     
     TableColumn columna3 = pago.tablaFact.getColumnModel().getColumn(2);
     columna3.setHeaderValue("NIT");
     
    System.out.println(" antes de entrar al llenado de columnas");
    
    modelo.setValueAt( RegDF.getnombreFact(), 0, 0);
    modelo.setValueAt( RegDF.getdireccionFact(), 0, 1);
    modelo.setValueAt( RegDF.getnitFact(), 0, 2);
    
    /*
     modelo.addRow(new Object[]{
    RegDF.getnombreFact(),RegDF.getdireccionFact(),RegDF.getnitFact()
    });   
    */

    ///Esto de aqui abajo no se debe tocar 
    pago.tablaFact.getTableHeader().repaint();      
    }//GEN-LAST:event_jButton9ActionPerformed
int numerodeFactura=0;

double Verdad=0;
    private void imprimirfactura(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimirfactura
        // TODO add your handling code here:
     
        String temp1=pago.totalFacturar.getText();
        double temp2=Cot.getOperacion();
        double convertTemp1=Double.parseDouble(temp1);
        Verdad=temp2+convertTemp1;
        
        String codigoA=cadena55;
        
        String temporalO=Cot.getOrigenF();
            String tempMO=Cot.getMunO();    
        String temporalD=Cot.getDestinoF();
            String tempMD=Cot.getMunD();
        String temporalnit=RegDF.getNitfactura();
        String temporalPago=pago.getTipodpago();
        String temporalTamaño=Cot.getTamañoPaqueteF();
        String temporalNumP=Cot.getNumeroPaquetesF();
       //Aqui hago lo de la fecha
       
       
        
    numerodeFactura=numerodeFactura+1;
    StringBuilder html = new StringBuilder();
    html.append("<html>");
        html.append("<head><title>Factura UsacDelivery </title></head>");
        html.append("<body><h1>_______FACTURA_______</h1></body>");
        //Numero de Factura
        html.append("<body><h1>Numero de Factura</h1></body>");
        html.append("<p>"+numerodeFactura+"</p>");
        //Codigo de Paquete                                        aun tengo pendiente el odigo
        html.append("<body><h1>Codigo de Paquete</h1></body>");
        html.append("<p>"+codigoA+"</p>");
        //Origen
        html.append("<body><h1>Origen</h1></body>");
        html.append("<p>"+temporalO+" en su municipio: "+tempMO+"</p>");
        //Destino
        html.append("<body><h1>Destino</h1></body>");
        html.append("<p>"+temporalD+" en su municipio: "+tempMD+"</p>");
        //NIT
        html.append("<body><h1>Nit</h1></body>");               // En esta linea tengo dudas con el nit
        html.append("<p>"+temporalnit+"</p>");
        //Tipo de Pago
        html.append("<body><h1>Tipo de Pago</h1></body>");
        html.append("<p>"+temporalPago+"</p>");
        //Tamaño de Paquete
        html.append("<body><h1>Tamaño de Paquete</h1></body>");
        html.append("<p>"+temporalTamaño+"</p>");
        //Numero de Paquetes
        html.append("<body><h1>Numero de Paquetes</h1></body>");
        html.append("<p>"+temporalNumP+"</p>");
        //Total a pagar 
        html.append("<body><h1>Total de la Factura</h1></body>");
        html.append("<p>"+Verdad+"</p>");
        
        
        try{
            File file = new File("src/TodosLosObjetos/VentanaPrincipal/Factura.html");
            FileWriter writer = new FileWriter(file);
            writer.write(html.toString());
            writer.close();
        }catch(IOException e){
            e.printStackTrace();
        }
        JOptionPane.showMessageDialog(null, "Su Factura fue generada, la encontrata en html dentro de la carpeta de este archivo");
   
    }//GEN-LAST:event_imprimirfactura

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        cambiarpaneles(Cot);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        cambiarpaneles(RegDF);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        cambiarpaneles(RegT);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        //elec 1 es para que imprima guia
        //Aqui hago la fecha
        LocalDate fechaActual=LocalDate.now();
        
           //String temp1=pago.totalFacturar.getText();
        double temp2=Cot.getOperacion();
        double convertTemp1=Double.parseDouble(temp1);
        double Verdad=temp2+convertTemp1;
        
        //LocalDate fechaActual = LocalDate.now();
        String cod=cadena55;
        String temporalO=Cot.getOrigenF();
            String tempMO=Cot.getMunO();    
        String temporalD=Cot.getDestinoF();
            String tempMD=Cot.getMunD();
        String temporalnit=RegDF.getNitfactura();
        String temporalPago=pago.getTipodpago();
        String temporalTamaño=Cot.getTamañoPaqueteF();
        String temporalNumP=Cot.getNumeroPaquetesF();
        //String temporalTotal=pago.getTotalFacturaFinal();
        
        //double tempT=pago.getVerdaderoTotal();
        
    numerodeFactura=numerodeFactura+1;
    StringBuilder html = new StringBuilder();
    html.append("<html>");
        html.append("<head><title>GUIA UsacDelivery</title> </head>");
        html.append("<body><h1>_______GUIA_______</h1></body>");
      
        //Codigo de Paquete                                        aun tengo pendiente el odigo
        html.append("<body><h1>Codigo de Paquete</h1></body>");
        html.append("<p>"+cod+"</p>");
        
        //Origen
        html.append("<body><h1>Origen</h1></body>");
        html.append("<p>"+temporalO+" en su municipio: "+tempMO+"</p>");
        
        //Destino
        html.append("<body><h1>Destino</h1></body>");
        html.append("<p>"+temporalD+" en su municipio: "+tempMD+"</p>");
        
        //Tipo de Pago
        html.append("<body><h1>Tipo de Pago</h1></body>");
        html.append("<p>"+temporalPago+"</p>");
        
        //Tamaño de Paquete
        html.append("<body><h1>Tamaño de Paquete</h1></body>");
        html.append("<p>"+temporalTamaño+"</p>");
        
        //Numero de Paquetes
        html.append("<body><h1>Numero de Paquetes</h1></body>");
        html.append("<p>"+temporalNumP+"</p>");
        
        //Fecha de envio
        html.append("<body><h1>Fecha de Envio</h1></body>");
        html.append("<p>"+fechaActual+"</p>");
        
        //Total a pagar 
        html.append("<body><h1>Total de la Factura</h1></body>");
        html.append("<p>"+Verdad+"</p>");
        
        
        try{
            File file = new File("src/TodosLosObjetos/VentanaPrincipal/Guia.html");
            FileWriter writer = new FileWriter(file);
            writer.write(html.toString());
            writer.close();
        }catch(IOException e){
            e.printStackTrace();
        }
        JOptionPane.showMessageDialog(null, "Su guia fue generada, la encontrata en html dentro de la carpeta de este archivo");
   
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        cambiarpaneles(PregistroU);
    }//GEN-LAST:event_jButton10ActionPerformed
                                         
 public static String generarCadena() {
        String primerosCinco = "IPC1C";
        String ultimosCinco = generarCadenaAleatoria(5);
        return primerosCinco + ultimosCinco;
    }
    public static String generarCadenaAleatoria(int longitud) {
        String caracteresPermitidos = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_";
        Random rnd = new Random();
        StringBuilder sb = new StringBuilder(longitud);
        for (int i = 0; i < longitud; i++) {
            int indice = rnd.nextInt(caracteresPermitidos.length());
            sb.append(caracteresPermitidos.charAt(indice));
            caracteresPermitidos = caracteresPermitidos.substring(0, indice) + caracteresPermitidos.substring(indice + 1);
        }
        return sb.toString();
    }
String cadena55="";
int M=0;
int NT=0;
int NO=0;
int SO=0;
int SOC=0;
int NOC=0;
int paquetesR=0;
double totalR=0;

    public int getM() {
        return M;
    }

    public void setM(int M) {
        this.M = M;
    }

    public int getNT() {
        return NT;
    }

    public void setNT(int NT) {
        this.NT = NT;
    }

    public int getNO() {
        return NO;
    }

    public void setNO(int NO) {
        this.NO = NO;
    }

    public int getSO() {
        return SO;
    }

    public void setSO(int SO) {
        this.SO = SO;
    }

    public int getSOC() {
        return SOC;
    }

    public void setSOC(int SOC) {
        this.SOC = SOC;
    }

    public int getNOC() {
        return NOC;
    }

    public void setNOC(int NOC) {
        this.NOC = NOC;
    }

    public int getPaquetesR() {
        return paquetesR;
    }

    public void setPaquetesR(int paquetesR) {
        this.paquetesR = paquetesR;
    }

    public double getTotalR() {
        return totalR;
    }

    public void setTotalR(double totalR) {
        this.totalR = totalR;
    }

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        String cadena = generarCadena();
        cadena55=cadena;
        int temporalNumPaquetes=Integer. parseInt(Cot.getNumeroPaquetesF());
        
        //Obtengo el destino final/Region
        String temporalD=Cot.getDestinoF();
        //Obtengo el numero de paqutes general
        paquetesR=paquetesR+temporalNumPaquetes;
        //Total de todos los envio
        totalR=totalR+Verdad;
        //Region Metropolitana
        if((temporalD.equals("Guatemala"))){
            M=M+1;
        }
        //Region Norte 
        else if((temporalD.equals("Alta Verapaz"))||(temporalD.equals("Baja Verapaz"))||(temporalD.equals("Petén"))){
            NT=NT+1;
        }
        //Region NorOriente
        else if((temporalD.equals("Chiquimula"))||(temporalD.equals("El Progreso"))
                ||(temporalD.equals("Izabal"))||(temporalD.equals("Zacapa"))){
            NO=NO+1;
        }
        //Region SurOriente
        else if((temporalD.equals("Jutiapa"))||(temporalD.equals("Jalapa"))
                ||(temporalD.equals("Santa Rosa"))){
            SO=SO+1;
        }
        //Region SurOccidente
        else if((temporalD.equals("Quetzaltenango"))||(temporalD.equals("Retalhuleu"))
                ||(temporalD.equals("San Marcos"))||(temporalD.equals("Totonicapán"))
                ||(temporalD.equals("Suchitepéquez"))||(temporalD.equals("Chimaltenango"))
                ||(temporalD.equals("Escuintla"))||(temporalD.equals("Sololá"))){
            SOC=SOC+1;
        }
        //Region NorOccidente
        else if((temporalD.equals("Huehuetenango"))||(temporalD.equals("Quiché"))
                ||(temporalD.equals("Sacatepéquez"))){
           NOC=NOC+1;
        }
        jButton11.setVisible(false);
        bgeneralU.setVisible(false);
        //cambiarpaneles(EnT);
        seguirB.setVisible(true);
        
    }//GEN-LAST:event_jButton11ActionPerformed

    private void seguirBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seguirBActionPerformed
        // TODO add your handling code here:
        subPanel.setVisible(false);
        cambiarpaneles(panelU);
        seguirB.setVisible(false);
        bgeneralU.setVisible(true);
    }//GEN-LAST:event_seguirBActionPerformed
    
   
    //nombre del objeto que llama al panel RegistroDatosFacturacion
    
    //nombre del objeto que llama al panel Corizacion
   
    Pago pago=new Pago();    
      
    MostrarKioskos MK = new MostrarKioskos();
    
    
    

    //Hacer un metodo para poder intercambiar los paneles
    private void cambiarpaneles(javax.swing.JPanel MiPanel) {
        //tengo que asegurarme que el panel que voy a meter me tiene que caber en el espacio en donde voy a intePusuarioclienter los paneles
        //572, 360, es el tamaño que actualmente tiene el panel que voy a quitar
        //Mi panel es el panel que le voy a mandar
        MiPanel.setSize(800, 410);  //lo unico que hago es darle tamaño a el panel que le voy a mandar 
        MiPanel.setLocation(0, 0);//indico el punto donde se va a ubicar dentro del panel, el cual estoy intercambiando. normalmente se pone punto o,o
        //ahora debo poner el nombre variable del panel que voy a quitar o sustituir
        PanelPrincipal.removeAll(); //esta accion dice que va a limpiar lo que sea que tenga este panel, para dejarlo limpio
        //ahora como en este mismo panel voy a poner los demas paneles, le pongo la siguiente sintaxis
        PanelPrincipal.add(MiPanel); //se pone mi panel, porque es el panel que le estoy mandando  "BorderLayour.CENTER" hace que ponga el panel que le mando lo centre en el panel pincipal
        PanelPrincipal.revalidate();//esto lo que hace es volver a darle estilo al panel
        PanelPrincipal.repaint(); //esto como que le dice que lo dibuje.

        //La finalidad de este metodo, es darle un tamaño al panel que estoy mandando, va a limpiar el pane existente, le damos la ubicacion, que vuelva a tomar un diseño y que lo pinte o muestre.
    }
    //
    // creo un metodo igual, pero este me servira para mostrar y ocular los botones 
    /*
        private void cambiarpanelesB(javax.swing.JPanel MiPanelB){
    MiPanelB.setSize(450,75);
    MiPanelB.setLocation(0,0);
    Pbotones.removeAll();
    Pbotones
    }
     */
  //RegistroTarjeta RT=new RegistroTarjeta();
    //Varibles de los paneles 
    
    
    Guia Pguia=new Guia();
    
    EncioTerminado EnT=new EncioTerminado();
    Cotizacion Cot=new Cotizacion();
    RegistroDatosFacturacion RegDT =new RegistroDatosFacturacion();
    ReporteAdmin repAdmin=new ReporteAdmin();
    RegistroDatosFacturacion RegDF =new RegistroDatosFacturacion();
    RegistoTarjeta RegT= new RegistoTarjeta();
    PanelUsuario panelU = new PanelUsuario();
    PrincipalAdmin Padmin = new PrincipalAdmin();
    RegistroUsuarios PregistroU = new RegistroUsuarios();
    login login = new login();
    IngresoKiosko Ikiosko = new IngresoKiosko();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BagregarAkiosko;
    private javax.swing.JButton Bcrearusuario;
    private javax.swing.JButton Biniciarsesion;
    private javax.swing.JButton Blogin;
    private javax.swing.JButton Bmostarkiosko;
    private javax.swing.JPanel PBadmin;
    private javax.swing.JPanel PBinicio;
    private javax.swing.JPanel PBkiosko;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JPanel bgeneralU;
    private javax.swing.JButton entrarKiosko;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel mensajedesesion;
    private javax.swing.JButton seguirB;
    private javax.swing.JPanel subPanel;
    // End of variables declaration//GEN-END:variables

    @Override
    public int print(Graphics graf, PageFormat pagfor, int index) throws PrinterException {
  
        if(index>0){
            return NO_SUCH_PAGE;
        }
        Graphics2D hub=(Graphics2D) graf;
        hub.translate(pagfor.getImageableX()+30, pagfor.getImageableY()+30);
        hub.scale(1.0,1.0);
        //En esta linea siguiente indico que panel quiero que se imprima
       // Pfactura.printAll(graf);
        return PAGE_EXISTS;
    }

    private static class EncioTerminado {

        public EncioTerminado() {
        }
    }
}
