/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Objeto.Paneles;

import java.awt.event.ItemEvent;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;


public class Cotizacion extends javax.swing.JPanel {

    
    public Cotizacion() {
        initComponents();
        comboMunO.setEnabled(false);
        ComboMunD.setEnabled(false);
        cotizacionT.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        comboDepO = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboMunO = new javax.swing.JComboBox<>();
        ComboMunD = new javax.swing.JComboBox<>();
        numPaquete = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        servicioEstandarT = new javax.swing.JLabel();
        checkEstandar = new javax.swing.JCheckBox();
        checkEspecial = new javax.swing.JCheckBox();
        precioEspecialT = new javax.swing.JLabel();
        comboDepD = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        librasT = new javax.swing.JTextField();
        cotizacionT = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(0, 0, 0));
        setPreferredSize(new java.awt.Dimension(1000, 446));

        comboDepO.setBackground(new java.awt.Color(255, 255, 255));
        comboDepO.setForeground(new java.awt.Color(0, 0, 0));
        comboDepO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar departamento", "Alta Verapaz", "Baja Verapaz", "Chimaltenango", "Chiquimula", "El Progreso", "Escuintla", "Guatemala", "Huehuetenango", "Izabal", "Jalapa", "Jutiapa", "Petén", "Quetzaltenango", "Quiché", "Retalhuleu", "Sacatepéquez", "San Marcos", "Santa Rosa", "Sololá", "Suchitepéquez", "Totonicapán", "Zacapa" }));
        comboDepO.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboDepOItemStateChanged(evt);
            }
        });
        comboDepO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDepOActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Origen");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Destino");

        comboMunO.setBackground(new java.awt.Color(255, 255, 255));
        comboMunO.setForeground(new java.awt.Color(0, 0, 0));
        comboMunO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selesccionar municipio" }));
        comboMunO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMunOActionPerformed(evt);
            }
        });

        ComboMunD.setBackground(new java.awt.Color(255, 255, 255));
        ComboMunD.setForeground(new java.awt.Color(0, 0, 0));
        ComboMunD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selesccionar municipio" }));
        ComboMunD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboMunDActionPerformed(evt);
            }
        });

        numPaquete.setBackground(new java.awt.Color(255, 255, 255));
        numPaquete.setForeground(new java.awt.Color(0, 0, 0));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tamaño de Paquetes");

        jButton1.setBackground(new java.awt.Color(255, 255, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Cotizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        servicioEstandarT.setForeground(new java.awt.Color(0, 0, 0));
        servicioEstandarT.setText(".................");

        checkEstandar.setBackground(new java.awt.Color(255, 255, 255));
        checkEstandar.setForeground(new java.awt.Color(0, 0, 0));
        checkEstandar.setText("Servicio Estandar");

        checkEspecial.setBackground(new java.awt.Color(255, 255, 255));
        checkEspecial.setForeground(new java.awt.Color(0, 0, 0));
        checkEspecial.setText("Servicio Especial");

        precioEspecialT.setForeground(new java.awt.Color(0, 0, 0));
        precioEspecialT.setText(".............");

        comboDepD.setBackground(new java.awt.Color(255, 255, 255));
        comboDepD.setForeground(new java.awt.Color(0, 0, 0));
        comboDepD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar departamento", "Alta Verapaz", "Baja Verapaz", "Chimaltenango", "Chiquimula", "El Progreso", "Escuintla", "Guatemala", "Huehuetenango", "Izabal", "Jalapa", "Jutiapa", "Petén", "Quetzaltenango", "Quiché", "Retalhuleu", "Sacatepéquez", "San Marcos", "Santa Rosa", "Sololá", "Suchitepéquez", "Totonicapán", "Zacapa" }));
        comboDepD.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboDepDItemStateChanged(evt);
            }
        });
        comboDepD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDepDActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Numero de Paquetes ");

        librasT.setBackground(new java.awt.Color(255, 255, 255));
        librasT.setForeground(new java.awt.Color(0, 0, 0));

        cotizacionT.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cotizacionT.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(precioEspecialT, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(199, 199, 199))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel1))
                                    .addComponent(comboDepD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ComboMunD, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(53, 53, 53)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(comboDepO, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboMunO, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(numPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(librasT, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(checkEspecial)
                                        .addComponent(checkEstandar))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(410, 410, 410)
                                .addComponent(servicioEstandarT, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cotizacionT))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboDepO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboMunO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(librasT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel2)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboDepD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkEspecial))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboMunD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkEstandar))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(precioEspecialT)
                        .addComponent(cotizacionT))
                    .addComponent(servicioEstandarT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
        );
    }// </editor-fold>//GEN-END:initComponents

    String[] departamentos = {"Alta Verapaz", "Baja Verapaz", "Chimaltenango", "Chiquimula", "El Progreso", "Escuintla", "Guatemala", "Huehuetenango", "Izabal", "Jalapa", "Jutiapa", "Petén", "Quetzaltenango", "Quiché", "Retalhuleu", "Sacatepéquez", "San Marcos", "Santa Rosa", "Sololá", "Suchitepéquez", "Totonicapán", "Zacapa"};
    DefaultComboBoxModel<String> modeloDep = new DefaultComboBoxModel<>(departamentos);
//////////
    String[] departamentosD = {"Alta Verapaz", "Baja Verapaz", "Chimaltenango", "Chiquimula", "El Progreso", "Escuintla", "Guatemala", "Huehuetenango", "Izabal", "Jalapa", "Jutiapa", "Petén", "Quetzaltenango", "Quiché", "Retalhuleu", "Sacatepéquez", "San Marcos", "Santa Rosa", "Sololá", "Suchitepéquez", "Totonicapán", "Zacapa"};
    DefaultComboBoxModel<String> modeloDepD = new DefaultComboBoxModel<>(departamentosD);

    private void comboDepOItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboDepOItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if (this.comboDepO.getSelectedIndex() >= 0) {
                this.comboMunO.setModel(new DefaultComboBoxModel(this.getmuni(this.comboDepO.getSelectedItem().toString())));
            }
        }
    }//GEN-LAST:event_comboDepOItemStateChanged
    public String[] getmuni(String dep) {
        String[] municipios = new String[32];
        if (dep.equalsIgnoreCase("Guatemala")) {

            municipios[0] = "Chinautla";
            municipios[1] = "Chuarrancho";
            municipios[2] = "Fraijanes";
            municipios[3] = "Guatemala";
            municipios[4] = "Mixco";
            municipios[5] = "Palencia";
            municipios[6] = "Petapa";
            municipios[7] = "San José del Golfo";
            municipios[8] = "San José Pinula";
            municipios[9] = "San Juan Sacatepéquez";
            municipios[10] = "San Miguel Petapa";
            municipios[11] = "San Pedro Ayampuc";
            municipios[12] = "San Pedro Sacatepéquez";
            municipios[13] = "San Raymundo";
            municipios[14] = "Santa Catarina Pinula";
            municipios[15] = "Villa Nueva";
            municipios[16] = "Amatitlán";
            comboMunO.setEnabled(true);
        } else if (dep.equalsIgnoreCase("Chimaltenango")) {
            municipios[0] = "Acatenango";
            municipios[1] = "Chimaltenango";
            municipios[2] = "El Tejar";
            municipios[3] = "Parramos";
            municipios[4] = "Patzicía";
            municipios[5] = "Patzún";
            municipios[6] = "Pochuta";
            municipios[7] = "San Andrés Itzapa";
            municipios[8] = "San José Poaquil";
            municipios[9] = "San Juan Comalapa";
            municipios[10] = "San Martín Jilotepeque";
            municipios[11] = "Santa Apolonia";
            municipios[12] = "Santa Cruz Balanyá";
            municipios[13] = "Tecpán Guatemala";
            municipios[14] = "Yepocapa";
            municipios[15] = "Zaragoza";
            comboMunO.setEnabled(true);
        } else if (dep.equalsIgnoreCase("Sacatépequez")) {
            municipios[0] = "Alotenango";
            municipios[1] = "Antigua Guatemala";
            municipios[2] = "Ciudad Vieja";
            municipios[3] = "Jocotenango";
            municipios[4] = "Magdalena Milpas Altas";
            municipios[5] = "Pastores";
            municipios[6] = "San Antonio Aguas Calientes";
            municipios[7] = "San Bartolomé Milpas Altas";
            municipios[8] = "San Lucas Sacatepéquez";
            municipios[9] = "San Miguel Dueñas";
            municipios[10] = "Santa Catarina Barahona";
            municipios[11] = "Santa Lucía Milpas Altas";
            municipios[12] = "Santa María de Jesús";
            municipios[13] = "Santiago Sacatepéquez";
            municipios[14] = "Santo Domingo Xenacoj";
            municipios[15] = "Sumpango";
            comboMunO.setEnabled(true);
        } else if (dep.equalsIgnoreCase("Suchitepéquez")) {
            municipios[0] = "Chicacao";
            municipios[1] = "Cuyotenango";
            municipios[2] = "Mazatenango";
            municipios[3] = "Patulul";
            municipios[4] = "Pueblo Nuevo";
            municipios[5] = "Río Bravo";
            municipios[6] = "Samayac";
            municipios[7] = "San Antonio Suchitepéquez";
            municipios[8] = "San Bernardino";
            municipios[9] = "San Francisco Zapotitlán";
            municipios[10] = "San Gabriel";
            municipios[11] = "San José El Idolo";
            municipios[12] = "San Juan Bautista";
            municipios[13] = "San Lorenzo";
            municipios[14] = "San Miguel Panán";
            municipios[15] = "San Pablo Jocopilas";
            municipios[16] = "Santa Bárbara";
            municipios[17] = "Santo Domingo Suchitepéquez";
            municipios[18] = "Santo Tomás La Unión";
            municipios[19] = "Zunilito";

            comboMunO.setEnabled(true);
        } else if (dep.equalsIgnoreCase("Sololá")) {

            municipios[0] = "Sololá";
            municipios[1] = "San José Chacayá";
            municipios[2] = "Santa María Visitación";
            municipios[3] = "Santa Lucía Utatlán";
            municipios[4] = "Nahualá";
            municipios[5] = "Santa Catarina Ixtahuacán";
            municipios[6] = "Santa Clara La Laguna";
            municipios[7] = "Concepción";
            municipios[8] = "San Andrés Semetabaj";
            municipios[9] = "Panajachel";
            municipios[10] = "Santa Catarina Palopó";
            municipios[11] = "San Antonio Palopó";
            municipios[12] = "San Lucas Tolimán";
            municipios[13] = "Santa Cruz La Laguna";
            municipios[14] = "San Pablo La Laguna";
            municipios[15] = "San Juan La Laguna";
            municipios[16] = "San Marcos La Laguna";
            municipios[17] = "San Pedro La Laguna";
            municipios[18] = "Santiago Atitlán";
            comboMunO.setEnabled(true);
        } else if (dep.equalsIgnoreCase("Retalhuleu")) {
            municipios[0] = "Retalhuleu";
            municipios[1] = "Champerico";
            municipios[2] = "El Asintal";
            municipios[3] = "Nuevo San Carlos";
            municipios[4] = "San Andrés Villa Seca";
            municipios[5] = "San Felipe";
            municipios[6] = "San Martín Zapotitlán";
            municipios[7] = "San Sebastián";
            municipios[8] = "Santa Cruz Muluá";
            comboMunO.setEnabled(true);
        } else if (dep.equalsIgnoreCase("Escuintla")) {

            municipios[0] = "Escuintla";
            municipios[1] = "Santa Lucía Cotzumalguapa";
            municipios[2] = "La Democracia";
            municipios[3] = "Siquinalá";
            municipios[4] = "Masagua";
            municipios[5] = "Tiquisate";
            municipios[6] = "La Gomera";
            municipios[7] = "Guanagazapa";
            municipios[8] = "San José";
            municipios[9] = "Iztapa";
            municipios[10] = "Palín";
            municipios[11] = "San Vicente Pacaya";
            municipios[12] = "Nueva Concepción";
            comboMunO.setEnabled(true);
        } else if (dep.equalsIgnoreCase("El progreso")) {
            municipios[0] = "El Jícaro";
            municipios[1] = "Guastatoya";
            municipios[2] = "Morazán";
            municipios[3] = "San Agustín Acasaguastlán";
            municipios[4] = "San Antonio La Paz";
            municipios[5] = "San Cristóbal Acasaguastlán";
            municipios[6] = "Sanarate";
            municipios[7] = "Sansare";
            comboMunO.setEnabled(true);
        } else if (dep.equalsIgnoreCase("Quiché")) {
            municipios[0] = "Santa Cruz del Quiché";
            municipios[1] = "Canillá";
            municipios[2] = "Chajul";
            municipios[3] = "Chicamán";
            municipios[4] = "Chiché";
            municipios[5] = "Chichicastenango";
            municipios[6] = "Chinique";
            municipios[7] = "Cunén";
            municipios[8] = "Joyabaj";
            municipios[9] = "Nebaj";
            municipios[10] = "Pachalum";
            municipios[11] = "Patzité";
            municipios[12] = "Sacapulas";
            municipios[13] = "San Andrés Sajcabajá";
            municipios[14] = "San Antonio Ilotenango";
            municipios[15] = "San Bartolomé Jocotenango";
            municipios[16] = "San Juan Cotzal";
            municipios[17] = "San Pedro Jocopilas";
            municipios[18] = "Uspantán";
            municipios[19] = "Zacualpa";
            municipios[20] = "San Miguel Uspantán";
            comboMunO.setEnabled(true);
        } else if (dep.equalsIgnoreCase("Huehuetenango")) {

            municipios[0] = "Aguacatán";
            municipios[1] = "Chiantla";
            municipios[2] = "Colotenango";
            municipios[3] = "Concepción Huista";
            municipios[4] = "Cuilco";
            municipios[5] = "Huehuetenango";
            municipios[6] = "Jacaltenango";
            municipios[7] = "La Democracia";
            municipios[8] = "La Libertad";
            municipios[9] = "Malacatancito";
            municipios[10] = "Nentón";
            municipios[11] = "Petatán";
            municipios[12] = "San Antonio Huista";
            municipios[13] = "San Gaspar Ixchil";
            municipios[14] = "San Ildefonso Ixtahuacán";
            municipios[15] = "San Juan Atitán";
            municipios[16] = "San Juan Ixcoy";
            municipios[17] = "San Mateo Ixtatán";
            municipios[18] = "San Miguel Acatán";
            municipios[19] = "San Pedro Necta";
            municipios[20] = "San Pedro Soloma";
            municipios[21] = "San Rafael La Independencia";
            municipios[22] = "San Rafael Petzal";
            municipios[23] = "San Sebastián Coatán";
            municipios[24] = "San Sebastián Huehuetenango";
            municipios[25] = "Santa Ana Huista";
            municipios[26] = "Santa Bárbara";
            municipios[27] = "Santa Cruz Barillas";
            municipios[28] = "Santa Eulalia";
            municipios[29] = "Santiago Chimaltenango";
            municipios[30] = "Tectitán";
            municipios[31] = "Todos Santos Cuchumatán";
            comboMunO.setEnabled(true);
        } else if (dep.equalsIgnoreCase("Petén")) {
            municipios[0] = "Dolores";
            municipios[1] = "Flores";
            municipios[2] = "La Libertad";
            municipios[3] = "Melchor de Mencos";
            municipios[4] = "Poptún";
            municipios[5] = "San Andrés";
            municipios[6] = "San Benito";
            municipios[7] = "San Francisco";
            municipios[8] = "San José";
            municipios[9] = "San Luis";
            municipios[10] = "Santa Ana";
            municipios[11] = "Sayaxché";
            municipios[12] = "Tikal";
            municipios[13] = "El Chal";

            comboMunO.setEnabled(true);
        } else if (dep.equalsIgnoreCase("Izabal")) {
            municipios[0] = "Puerto Barrios";
            municipios[1] = "Livingston";
            municipios[2] = "El Estor";
            municipios[3] = "Morales";
            municipios[4] = "Los Amates";
            comboMunO.setEnabled(true);
        } else if (dep.equalsIgnoreCase("Jalapa")) {
            municipios[0] = "Jalapa";
            municipios[1] = "San Pedro Pinula";
            municipios[2] = "San Luis Jilotepeque";
            municipios[3] = "San Manuel Chaparrón";
            municipios[4] = "San Carlos Alzatate";
            municipios[5] = "Monjas";
            municipios[6] = "Mataquescuintla";
            comboMunO.setEnabled(true);
        } else if (dep.equalsIgnoreCase("Jutiapa")) {
            municipios[0] = "Jutiapa";
            municipios[1] = "Agua Blanca";
            municipios[2] = "Asunción Mita";
            municipios[3] = "Atescatempa";
            municipios[4] = "Comapa";
            municipios[5] = "Conguaco";
            municipios[6] = "El Adelanto";
            municipios[7] = "El Progreso";
            municipios[8] = "Jalpatagua";
            municipios[9] = "Jerez";
            municipios[10] = "Moyuta";
            municipios[11] = "Pasaco";
            municipios[12] = "Quezada";
            municipios[13] = "San José Acatempa";
            municipios[14] = "Santa Catarina Mita";
            municipios[15] = "Yupiltepeque";
            municipios[16] = "Zapotitlán";

            comboMunO.setEnabled(true);
        } else if (dep.equalsIgnoreCase("Quetzaltenango")) {
            municipios[0] = "Quetzaltenango";
            municipios[1] = "Almolonga";
            municipios[2] = "Cabricán";
            municipios[3] = "Cajolá";
            municipios[4] = "Cantel";
            municipios[5] = "Coatepeque";
            municipios[6] = "Colomba";
            municipios[7] = "Concepción Chiquirichapa";
            municipios[8] = "El Palmar";
            municipios[9] = "Flores Costa Cuca";
            municipios[10] = "Génova";
            municipios[11] = "Huitán";
            municipios[12] = "La Esperanza";
            municipios[13] = "Olintepeque";
            municipios[14] = "Ostuncalco";
            municipios[15] = "Palestina de Los Altos";
            municipios[16] = "Quetzaltenango";
            municipios[17] = "Salamatá";
            municipios[18] = "San Andrés Xecul";
            municipios[19] = "San Carlos Sija";
            municipios[20] = "San Francisco La Unión";
            municipios[21] = "San Juan Ostuncalco";
            municipios[22] = "San Mateo";
            municipios[22] = "Zunil";
            comboMunO.setEnabled(true);
        } else if (dep.equalsIgnoreCase("Santa Rosa")) {

            municipios[0] = "Santa Rosa de Lima";
            municipios[1] = "Pueblo Nuevo Viñas";
            municipios[2] = "Nueva Santa Rosa";
            municipios[3] = "Oratorio";
            municipios[4] = "San Juan Tecuaco";
            municipios[5] = "Cuilapa";
            municipios[6] = "Barberena";
            municipios[7] = "San Rafael Las Flores";
            municipios[8] = "Casillas";
            municipios[9] = "San Cristóbal Cucho";
            municipios[10] = "Santa María Ixhuatán";
            municipios[11] = "Guazacapán";
            municipios[12] = "Chiquimulilla";
            municipios[13] = "Taxisco";
            municipios[13] = "Santa Cruz Naranjo  ";

            comboMunO.setEnabled(true);
        } else if (dep.equalsIgnoreCase("Alta Verapaz")) {

            municipios[0] = "Chahal";
            municipios[1] = "Chisec";
            municipios[2] = "Cobán";
            municipios[3] = "Fray Bartolomé de las Casas";
            municipios[4] = "La Tinta";
            municipios[5] = "Lanquín";
            municipios[6] = "Panzós";
            municipios[7] = "Raxruhá";
            municipios[8] = "Sacapulas";
            municipios[9] = "San Cristóbal Verapaz";
            municipios[10] = "San Juan Chamelco";
            municipios[11] = "San Pedro Carchá";
            municipios[12] = "Santa Cruz Verapaz";
            municipios[13] = "Santa María Cahabón";
            municipios[14] = "Senahú";
            municipios[15] = "Tactic";
            municipios[16] = "Tucurú";
            comboMunO.setEnabled(true);
        } else if (dep.equalsIgnoreCase("Baja Verapaz")) {
            municipios[0] = "Cubulco";
            municipios[1] = "Granados";
            municipios[2] = "Purulhá";
            municipios[3] = "Rabinal";
            municipios[4] = "Salamá";
            municipios[5] = "San Jerónimo";
            municipios[6] = "San Miguel Chicaj";
            municipios[7] = "Santa Cruz El Chol";
            comboMunO.setEnabled(true);
        } else if (dep.equalsIgnoreCase("Chiquimula")) {
            municipios[0] = "Chiquimula";
            municipios[1] = "Camotán";
            municipios[2] = "Concepción Las Minas";
            municipios[3] = "Esquipulas";
            municipios[4] = "Jocotán";
            municipios[5] = "Olopa";
            municipios[6] = "Quezaltepeque";
            municipios[7] = "San Jacinto";
            municipios[8] = "San José La Arada";
            municipios[9] = "San Juan Ermita";
            municipios[10] = "Zacapa";

        } else if (dep.equalsIgnoreCase("Zacapa")) {
            municipios[0] = "Cabañas";
            municipios[1] = "Estanzuela";
            municipios[2] = "Gualán";
            municipios[3] = "Huité";
            municipios[4] = "La Unión";
            municipios[5] = "Río Hondo";
            municipios[6] = "San Diego";
            municipios[7] = "Zacapa";
            municipios[8] = "San Jorge";
            municipios[9] = "Teculután";
            municipios[10] = "Usumatlán";

            comboMunO.setEnabled(true);
        } else if (dep.equalsIgnoreCase("Totonicapán")) {
            municipios[0] = "Momostenango";
            municipios[1] = "San Andrés Xecul";
            municipios[2] = "San Bartolo";
            municipios[3] = "San Cristóbal Totonicapán";
            municipios[4] = "San Francisco El Alto";
            municipios[5] = "Santa Lucía La Reforma";
            municipios[6] = "Santa María Chiquimula";
            municipios[7] = "Totonicapán";

            comboMunO.setEnabled(true);
        } else if (dep.equalsIgnoreCase("San Marcos")) {
            municipios[0] = "San Marcos";
            municipios[1] = "Ayutla";
            municipios[2] = "Catarina";
            municipios[3] = "Comitancillo";
            municipios[4] = "Concepción Tutuapa";
            municipios[5] = "El Quetzal";
            municipios[6] = "El Rodeo";
            municipios[7] = "Ixchiguan";
            municipios[8] = "La Reforma";
            municipios[9] = "Ixchiguán";
            municipios[10] = "Malacatán";
            municipios[11] = "Nuevo Progreso";
            municipios[12] = "Ocós";
            municipios[13] = "Pajapita";
            municipios[14] = "Esquipulas Palo Gordo";
            municipios[15] = "San Antonio Sacatepéquez";
            municipios[16] = "San Cristóbal Cucho";
            municipios[17] = "San José Ojetenam";
            municipios[18] = "San Lorenzo";
            municipios[19] = "San Miguel Ixtahuacán";
            municipios[20] = "San Pablo";
            municipios[21] = "San Pedro Sacatepéquez";
            municipios[22] = "San Rafael Pie de La Cuesta";
            municipios[23] = "Sipacapa";
            municipios[24] = "San Sebastián";
            municipios[25] = "Tacaná";
            municipios[26] = "Tajumulco";
            municipios[27] = "Tejutla";
            municipios[28] = "Río Blanco";
            municipios[29] = "La Blanca";

            comboMunO.setEnabled(true);
        }
        return municipios;    //cbpaises es el nombre de su combo princioal
    }


    private void comboDepOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDepOActionPerformed
        // TODO add your handling code here:
        comboDepO.setModel(modeloDep);
    }//GEN-LAST:event_comboDepOActionPerformed

    private void comboDepDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDepDActionPerformed
        // TODO add your handling code here:
        comboDepD.setModel(modeloDepD);
        String seleccion = (String) comboDepD.getSelectedItem();

        //Region Metropolitana  Estandar es Q35.00 y el Especial es Q25.00
        if (seleccion.equals(("Guatemala"))) {
            servicioEstandarT.setText("35");
            precioEspecialT.setText("25");
        } //Region Norte  Estandar es Q68:50 y el Especial es Q45.55
        else if (seleccion.equals(("Alta Verapaz")) || seleccion.equals(("Baja Verapaz"))
                || seleccion.equals(("Petén"))) {
            servicioEstandarT.setText("68.50");
            precioEspecialT.setText("45.55");
        } //Region Nor Oriente Estandar es Q58.68  Escpecial Q35.48
        else if (seleccion.equals(("Chiquimula")) || seleccion.equals(("El Progreso"))
                || seleccion.equals(("Izabal")) || seleccion.equals(("Zacapa"))) {
            servicioEstandarT.setText("58.68");
            precioEspecialT.setText("35.48");
        }//Region Sur Oriente  Estandar es Q38.68  Escpecial Q32.48
        else if (seleccion.equals(("Jutiapa")) || seleccion.equals(("Jalapa"))
                || seleccion.equals(("Santa Rosa"))) {
            servicioEstandarT.setText("38.68");
            precioEspecialT.setText("32.48");
        }//Region Sur Occidente  Estandar es Q34  Escpecial Q29
        else if (seleccion.equals(("Quetzaltenango")) || seleccion.equals(("Retalhuleu"))
                || seleccion.equals(("San Marcos")) || seleccion.equals(("Totonicapán"))
                || seleccion.equals(("Suchitepéquez")) || seleccion.equals(("Chimaltenango")) 
                || seleccion.equals(("Escuintla")) || seleccion.equals(("Sololá"))) {
            servicioEstandarT.setText("34");
            precioEspecialT.setText("29");
        }//Region Nor Occidente Estandar es Q44.50 Escpecial 40
        else if (seleccion.equals(("Huehuetenando")) || seleccion.equals(("Quiché"))
                || seleccion.equals(("Sacatepéquez"))) {
            servicioEstandarT.setText("44.50");
            precioEspecialT.setText("40");
        }


    }//GEN-LAST:event_comboDepDActionPerformed

    private void comboDepDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboDepDItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if (this.comboDepD.getSelectedIndex() > 0) {
                this.ComboMunD.setModel(new DefaultComboBoxModel(this.getmuniD(this.comboDepD.getSelectedItem().toString())));
            }
        }

    }//GEN-LAST:event_comboDepDItemStateChanged

    private void comboMunOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMunOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboMunOActionPerformed

    private void ComboMunDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboMunDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboMunDActionPerformed
String munO="";
String munD="";

    public String getMunO() {
        return munO;
    }

    public void setMunO(String munO) {
        this.munO = munO;
    }

    public String getMunD() {
        return munD;
    }

    public void setMunD(String munD) {
        this.munD = munD;
    }
    
String tipoServicio="";
String Total="";
String OrigenF="";
String DestinoF="";
String TipoPagoF="";
String TamañoPaqueteF;
String numeroPaquetesF;

    public String getOrigenF() {
        return OrigenF;
    }

    public void setOrigenF(String OrigenF) {
        this.OrigenF = OrigenF;
    }

    public String getDestinoF() {
        return DestinoF;
    }

    public void setDestinoF(String DestinoF) {
        this.DestinoF = DestinoF;
    }

    public String getTipoPagoF() {
        return TipoPagoF;
    }

    public void setTipoPagoF(String TipoPagoF) {
        this.TipoPagoF = TipoPagoF;
    }

    public String getTamañoPaqueteF() {
        return TamañoPaqueteF;
    }

    public void setTamañoPaqueteF(String TamañoPaqueteF) {
        this.TamañoPaqueteF = TamañoPaqueteF;
    }

    public String getNumeroPaquetesF() {
        return numeroPaquetesF;
    }

    public void setNumeroPaquetesF(String numeroPaquetesF) {
        this.numeroPaquetesF = numeroPaquetesF;
    }

    double operacion=0;

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (((!checkEstandar.isSelected()) || (!checkEspecial.isSelected())) && (!librasT.getText().isEmpty()) && (!numPaquete.getText().isEmpty())) {
            String peso = librasT.getText();
            String cantidad = numPaquete.getText().trim();
            if ((peso.matches("^\\d*\\.?\\d+$")) && (cantidad.matches("\\d+"))) {
                // "^\\d*\\.?\\d+$"
                System.out.println(cantidad);
                System.out.println("enttro 1");
                if (checkEstandar.isSelected()) {
                    String libraTemS = librasT.getText();
                    String numPTemS = numPaquete.getText();
                    double libraTemD = Double.parseDouble(libraTemS);
                    double numPTemD = Double.parseDouble(numPTemS);
                    double precio = Double.parseDouble(servicioEstandarT.getText());
            //        double operacion;
                    operacion = libraTemD * numPTemD * precio;
                    cotizacionT.setText(String.valueOf(operacion));
                    
                    //datos para factura
                    OrigenF=(String)comboDepO.getSelectedItem();
                    munO=(String)comboMunO.getSelectedItem();
                    DestinoF=(String)comboDepD.getSelectedItem();
                    munD=(String)ComboMunD.getSelectedItem();
                    double pag =Double.parseDouble(librasT.getText());
                    if(pag>0&&pag<11){
                        TamañoPaqueteF="Peso Pequeño";}
                    else if(pag>10&&pag<51){
                        TamañoPaqueteF="Peso Mediano"; }
                    else if(pag>50){
                        TamañoPaqueteF="Peso Grande";
;                    }
                    numeroPaquetesF=numPaquete.getText();
                    
                    
                    
                    tipoServicio="Servicio Estandar";
                    Total=String.valueOf(cotizacionT.getText());
                    JOptionPane.showMessageDialog(null, "El monto a pagar es de: Q" + cotizacionT.getText());
                    
                } else if (checkEspecial.isSelected()) {
                    String libraTemS = librasT.getText();
                    String numPTemS = numPaquete.getText();
                    double libraTemD = Double.parseDouble(libraTemS);
                    double numPTemD = Double.parseDouble(numPTemS);
                    double precio1 = Double.parseDouble(precioEspecialT.getText());
          //          double operacion;
                    operacion = libraTemD * numPTemD * precio1;
                    cotizacionT.setText(String.valueOf(operacion));
                    tipoServicio="Servicio Especial";
                    Total=String.valueOf(cotizacionT.getText());
                    
                      //datos para factura
                    OrigenF=(String)comboDepO.getSelectedItem();
                    DestinoF=(String)comboDepD.getSelectedItem();
                    
                    double pag =Double.parseDouble(librasT.getText());
                    if(pag>0&&pag<11){
                        TamañoPaqueteF="Peso Pequeño";}
                    else if(pag>10&&pag<51){
                        TamañoPaqueteF="Peso Mediano"; }
                    else if(pag>50){
                        TamañoPaqueteF="Peso Grande";
;                    }
                    numeroPaquetesF=numPaquete.getText();
                    JOptionPane.showMessageDialog(null, "El monto a pagar es de: Q" + cotizacionT.getText());
                }

            } else {
                JOptionPane.showMessageDialog(null, "Usted solo puede escribir valores numericos en los Campos "
                        + "de peso y cantidad, porfavor intente de nuevo ");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe selecionar las casillas correspondientes");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public double getOperacion() {
        return operacion;
    }

    public void setOperacion(double operacion) {
        this.operacion = operacion;
    }

    
    
    public String getTipoServicio() {
        return tipoServicio;
    }

    public String getTotal() {
        return Total;
    }
    
    
    
    
    public String[] getmuniD(String depD) {
        String[] municipios = new String[32];
        if (depD.equalsIgnoreCase("Guatemala")) {

            municipios[0] = "Chinautla";
            municipios[1] = "Chuarrancho";
            municipios[2] = "Fraijanes";
            municipios[3] = "Guatemala";
            municipios[4] = "Mixco";
            municipios[5] = "Palencia";
            municipios[6] = "Petapa";
            municipios[7] = "San José del Golfo";
            municipios[8] = "San José Pinula";
            municipios[9] = "San Juan Sacatepéquez";
            municipios[10] = "San Miguel Petapa";
            municipios[11] = "San Pedro Ayampuc";
            municipios[12] = "San Pedro Sacatepéquez";
            municipios[13] = "San Raymundo";
            municipios[14] = "Santa Catarina Pinula";
            municipios[15] = "Villa Nueva";
            municipios[16] = "Amatitlán";
            ComboMunD.setEnabled(true);
        } else if (depD.equalsIgnoreCase("Chimaltenango")) {
            municipios[0] = "Acatenango";
            municipios[1] = "Chimaltenango";
            municipios[2] = "El Tejar";
            municipios[3] = "Parramos";
            municipios[4] = "Patzicía";
            municipios[5] = "Patzún";
            municipios[6] = "Pochuta";
            municipios[7] = "San Andrés Itzapa";
            municipios[8] = "San José Poaquil";
            municipios[9] = "San Juan Comalapa";
            municipios[10] = "San Martín Jilotepeque";
            municipios[11] = "Santa Apolonia";
            municipios[12] = "Santa Cruz Balanyá";
            municipios[13] = "Tecpán Guatemala";
            municipios[14] = "Yepocapa";
            municipios[15] = "Zaragoza";
            ComboMunD.setEnabled(true);
        } else if (depD.equalsIgnoreCase("Sacatépequez")) {
            municipios[0] = "Alotenango";
            municipios[1] = "Antigua Guatemala";
            municipios[2] = "Ciudad Vieja";
            municipios[3] = "Jocotenango";
            municipios[4] = "Magdalena Milpas Altas";
            municipios[5] = "Pastores";
            municipios[6] = "San Antonio Aguas Calientes";
            municipios[7] = "San Bartolomé Milpas Altas";
            municipios[8] = "San Lucas Sacatepéquez";
            municipios[9] = "San Miguel Dueñas";
            municipios[10] = "Santa Catarina Barahona";
            municipios[11] = "Santa Lucía Milpas Altas";
            municipios[12] = "Santa María de Jesús";
            municipios[13] = "Santiago Sacatepéquez";
            municipios[14] = "Santo Domingo Xenacoj";
            municipios[15] = "Sumpango";
            ComboMunD.setEnabled(true);
        } else if (depD.equalsIgnoreCase("Suchitepéquez")) {
            municipios[0] = "Chicacao";
            municipios[1] = "Cuyotenango";
            municipios[2] = "Mazatenango";
            municipios[3] = "Patulul";
            municipios[4] = "Pueblo Nuevo";
            municipios[5] = "Río Bravo";
            municipios[6] = "Samayac";
            municipios[7] = "San Antonio Suchitepéquez";
            municipios[8] = "San Bernardino";
            municipios[9] = "San Francisco Zapotitlán";
            municipios[10] = "San Gabriel";
            municipios[11] = "San José El Idolo";
            municipios[12] = "San Juan Bautista";
            municipios[13] = "San Lorenzo";
            municipios[14] = "San Miguel Panán";
            municipios[15] = "San Pablo Jocopilas";
            municipios[16] = "Santa Bárbara";
            municipios[17] = "Santo Domingo Suchitepéquez";
            municipios[18] = "Santo Tomás La Unión";
            municipios[19] = "Zunilito";

            ComboMunD.setEnabled(true);
        } else if (depD.equalsIgnoreCase("Sololá")) {

            municipios[0] = "Sololá";
            municipios[1] = "San José Chacayá";
            municipios[2] = "Santa María Visitación";
            municipios[3] = "Santa Lucía Utatlán";
            municipios[4] = "Nahualá";
            municipios[5] = "Santa Catarina Ixtahuacán";
            municipios[6] = "Santa Clara La Laguna";
            municipios[7] = "Concepción";
            municipios[8] = "San Andrés Semetabaj";
            municipios[9] = "Panajachel";
            municipios[10] = "Santa Catarina Palopó";
            municipios[11] = "San Antonio Palopó";
            municipios[12] = "San Lucas Tolimán";
            municipios[13] = "Santa Cruz La Laguna";
            municipios[14] = "San Pablo La Laguna";
            municipios[15] = "San Juan La Laguna";
            municipios[16] = "San Marcos La Laguna";
            municipios[17] = "San Pedro La Laguna";
            municipios[18] = "Santiago Atitlán";
            ComboMunD.setEnabled(true);
        } else if (depD.equalsIgnoreCase("Retalhuleu")) {
            municipios[0] = "Retalhuleu";
            municipios[1] = "Champerico";
            municipios[2] = "El Asintal";
            municipios[3] = "Nuevo San Carlos";
            municipios[4] = "San Andrés Villa Seca";
            municipios[5] = "San Felipe";
            municipios[6] = "San Martín Zapotitlán";
            municipios[7] = "San Sebastián";
            municipios[8] = "Santa Cruz Muluá";
            ComboMunD.setEnabled(true);
        } else if (depD.equalsIgnoreCase("Escuintla")) {

            municipios[0] = "Escuintla";
            municipios[1] = "Santa Lucía Cotzumalguapa";
            municipios[2] = "La Democracia";
            municipios[3] = "Siquinalá";
            municipios[4] = "Masagua";
            municipios[5] = "Tiquisate";
            municipios[6] = "La Gomera";
            municipios[7] = "Guanagazapa";
            municipios[8] = "San José";
            municipios[9] = "Iztapa";
            municipios[10] = "Palín";
            municipios[11] = "San Vicente Pacaya";
            municipios[12] = "Nueva Concepción";
            ComboMunD.setEnabled(true);
        } else if (depD.equalsIgnoreCase("El progreso")) {
            municipios[0] = "El Jícaro";
            municipios[1] = "Guastatoya";
            municipios[2] = "Morazán";
            municipios[3] = "San Agustín Acasaguastlán";
            municipios[4] = "San Antonio La Paz";
            municipios[5] = "San Cristóbal Acasaguastlán";
            municipios[6] = "Sanarate";
            municipios[7] = "Sansare";
            ComboMunD.setEnabled(true);
        } else if (depD.equalsIgnoreCase("Quiché")) {
            municipios[0] = "Santa Cruz del Quiché";
            municipios[1] = "Canillá";
            municipios[2] = "Chajul";
            municipios[3] = "Chicamán";
            municipios[4] = "Chiché";
            municipios[5] = "Chichicastenango";
            municipios[6] = "Chinique";
            municipios[7] = "Cunén";
            municipios[8] = "Joyabaj";
            municipios[9] = "Nebaj";
            municipios[10] = "Pachalum";
            municipios[11] = "Patzité";
            municipios[12] = "Sacapulas";
            municipios[13] = "San Andrés Sajcabajá";
            municipios[14] = "San Antonio Ilotenango";
            municipios[15] = "San Bartolomé Jocotenango";
            municipios[16] = "San Juan Cotzal";
            municipios[17] = "San Pedro Jocopilas";
            municipios[18] = "Uspantán";
            municipios[19] = "Zacualpa";
            municipios[20] = "San Miguel Uspantán";
            ComboMunD.setEnabled(true);
        } else if (depD.equalsIgnoreCase("Huehuetenango")) {

            municipios[0] = "Aguacatán";
            municipios[1] = "Chiantla";
            municipios[2] = "Colotenango";
            municipios[3] = "Concepción Huista";
            municipios[4] = "Cuilco";
            municipios[5] = "Huehuetenango";
            municipios[6] = "Jacaltenango";
            municipios[7] = "La Democracia";
            municipios[8] = "La Libertad";
            municipios[9] = "Malacatancito";
            municipios[10] = "Nentón";
            municipios[11] = "Petatán";
            municipios[12] = "San Antonio Huista";
            municipios[13] = "San Gaspar Ixchil";
            municipios[14] = "San Ildefonso Ixtahuacán";
            municipios[15] = "San Juan Atitán";
            municipios[16] = "San Juan Ixcoy";
            municipios[17] = "San Mateo Ixtatán";
            municipios[18] = "San Miguel Acatán";
            municipios[19] = "San Pedro Necta";
            municipios[20] = "San Pedro Soloma";
            municipios[21] = "San Rafael La Independencia";
            municipios[22] = "San Rafael Petzal";
            municipios[23] = "San Sebastián Coatán";
            municipios[24] = "San Sebastián Huehuetenango";
            municipios[25] = "Santa Ana Huista";
            municipios[26] = "Santa Bárbara";
            municipios[27] = "Santa Cruz Barillas";
            municipios[28] = "Santa Eulalia";
            municipios[29] = "Santiago Chimaltenango";
            municipios[30] = "Tectitán";
            municipios[31] = "Todos Santos Cuchumatán";
            ComboMunD.setEnabled(true);
        } else if (depD.equalsIgnoreCase("Petén")) {
            municipios[0] = "Dolores";
            municipios[1] = "Flores";
            municipios[2] = "La Libertad";
            municipios[3] = "Melchor de Mencos";
            municipios[4] = "Poptún";
            municipios[5] = "San Andrés";
            municipios[6] = "San Benito";
            municipios[7] = "San Francisco";
            municipios[8] = "San José";
            municipios[9] = "San Luis";
            municipios[10] = "Santa Ana";
            municipios[11] = "Sayaxché";
            municipios[12] = "Tikal";
            municipios[13] = "El Chal";

            ComboMunD.setEnabled(true);
        } else if (depD.equalsIgnoreCase("Izabal")) {
            municipios[0] = "Puerto Barrios";
            municipios[1] = "Livingston";
            municipios[2] = "El Estor";
            municipios[3] = "Morales";
            municipios[4] = "Los Amates";
            ComboMunD.setEnabled(true);
        } else if (depD.equalsIgnoreCase("Jalapa")) {
            municipios[0] = "Jalapa";
            municipios[1] = "San Pedro Pinula";
            municipios[2] = "San Luis Jilotepeque";
            municipios[3] = "San Manuel Chaparrón";
            municipios[4] = "San Carlos Alzatate";
            municipios[5] = "Monjas";
            municipios[6] = "Mataquescuintla";
            ComboMunD.setEnabled(true);
        } else if (depD.equalsIgnoreCase("Jutiapa")) {
            municipios[0] = "Jutiapa";
            municipios[1] = "Agua Blanca";
            municipios[2] = "Asunción Mita";
            municipios[3] = "Atescatempa";
            municipios[4] = "Comapa";
            municipios[5] = "Conguaco";
            municipios[6] = "El Adelanto";
            municipios[7] = "El Progreso";
            municipios[8] = "Jalpatagua";
            municipios[9] = "Jerez";
            municipios[10] = "Moyuta";
            municipios[11] = "Pasaco";
            municipios[12] = "Quezada";
            municipios[13] = "San José Acatempa";
            municipios[14] = "Santa Catarina Mita";
            municipios[15] = "Yupiltepeque";
            municipios[16] = "Zapotitlán";

            ComboMunD.setEnabled(true);
        } else if (depD.equalsIgnoreCase("Quetzaltenango")) {
            municipios[0] = "Quetzaltenango";
            municipios[1] = "Almolonga";
            municipios[2] = "Cabricán";
            municipios[3] = "Cajolá";
            municipios[4] = "Cantel";
            municipios[5] = "Coatepeque";
            municipios[6] = "Colomba";
            municipios[7] = "Concepción Chiquirichapa";
            municipios[8] = "El Palmar";
            municipios[9] = "Flores Costa Cuca";
            municipios[10] = "Génova";
            municipios[11] = "Huitán";
            municipios[12] = "La Esperanza";
            municipios[13] = "Olintepeque";
            municipios[14] = "Ostuncalco";
            municipios[15] = "Palestina de Los Altos";
            municipios[16] = "Quetzaltenango";
            municipios[17] = "Salamatá";
            municipios[18] = "San Andrés Xecul";
            municipios[19] = "San Carlos Sija";
            municipios[20] = "San Francisco La Unión";
            municipios[21] = "San Juan Ostuncalco";
            municipios[22] = "San Mateo";
            municipios[22] = "Zunil";
            ComboMunD.setEnabled(true);
        } else if (depD.equalsIgnoreCase("Santa Rosa")) {

            municipios[0] = "Santa Rosa de Lima";
            municipios[1] = "Pueblo Nuevo Viñas";
            municipios[2] = "Nueva Santa Rosa";
            municipios[3] = "Oratorio";
            municipios[4] = "San Juan Tecuaco";
            municipios[5] = "Cuilapa";
            municipios[6] = "Barberena";
            municipios[7] = "San Rafael Las Flores";
            municipios[8] = "Casillas";
            municipios[9] = "San Cristóbal Cucho";
            municipios[10] = "Santa María Ixhuatán";
            municipios[11] = "Guazacapán";
            municipios[12] = "Chiquimulilla";
            municipios[13] = "Taxisco";
            municipios[13] = "Santa Cruz Naranjo  ";

            ComboMunD.setEnabled(true);
        } else if (depD.equalsIgnoreCase("Alta Verapaz")) {

            municipios[0] = "Chahal";
            municipios[1] = "Chisec";
            municipios[2] = "Cobán";
            municipios[3] = "Fray Bartolomé de las Casas";
            municipios[4] = "La Tinta";
            municipios[5] = "Lanquín";
            municipios[6] = "Panzós";
            municipios[7] = "Raxruhá";
            municipios[8] = "Sacapulas";
            municipios[9] = "San Cristóbal Verapaz";
            municipios[10] = "San Juan Chamelco";
            municipios[11] = "San Pedro Carchá";
            municipios[12] = "Santa Cruz Verapaz";
            municipios[13] = "Santa María Cahabón";
            municipios[14] = "Senahú";
            municipios[15] = "Tactic";
            municipios[16] = "Tucurú";
            ComboMunD.setEnabled(true);
        } else if (depD.equalsIgnoreCase("Baja Verapaz")) {
            municipios[0] = "Cubulco";
            municipios[1] = "Granados";
            municipios[2] = "Purulhá";
            municipios[3] = "Rabinal";
            municipios[4] = "Salamá";
            municipios[5] = "San Jerónimo";
            municipios[6] = "San Miguel Chicaj";
            municipios[7] = "Santa Cruz El Chol";
            ComboMunD.setEnabled(true);
        } else if (depD.equalsIgnoreCase("Chiquimula")) {
            municipios[0] = "Chiquimula";
            municipios[1] = "Camotán";
            municipios[2] = "Concepción Las Minas";
            municipios[3] = "Esquipulas";
            municipios[4] = "Jocotán";
            municipios[5] = "Olopa";
            municipios[6] = "Quezaltepeque";
            municipios[7] = "San Jacinto";
            municipios[8] = "San José La Arada";
            municipios[9] = "San Juan Ermita";
            municipios[10] = "Zacapa";
            ComboMunD.setEnabled(true);

        } else if (depD.equalsIgnoreCase("Zacapa")) {
            municipios[0] = "Cabañas";
            municipios[1] = "Estanzuela";
            municipios[2] = "Gualán";
            municipios[3] = "Huité";
            municipios[4] = "La Unión";
            municipios[5] = "Río Hondo";
            municipios[6] = "San Diego";
            municipios[7] = "Zacapa";
            municipios[8] = "San Jorge";
            municipios[9] = "Teculután";
            municipios[10] = "Usumatlán";

            ComboMunD.setEnabled(true);
        } else if (depD.equalsIgnoreCase("Totonicapán")) {
            municipios[0] = "Momostenango";
            municipios[1] = "San Andrés Xecul";
            municipios[2] = "San Bartolo";
            municipios[3] = "San Cristóbal Totonicapán";
            municipios[4] = "San Francisco El Alto";
            municipios[5] = "Santa Lucía La Reforma";
            municipios[6] = "Santa María Chiquimula";
            municipios[7] = "Totonicapán";

            ComboMunD.setEnabled(true);
        } else if (depD.equalsIgnoreCase("San Marcos")) {
            municipios[0] = "San Marcos";
            municipios[1] = "Ayutla";
            municipios[2] = "Catarina";
            municipios[3] = "Comitancillo";
            municipios[4] = "Concepción Tutuapa";
            municipios[5] = "El Quetzal";
            municipios[6] = "El Rodeo";
            municipios[7] = "Ixchiguan";
            municipios[8] = "La Reforma";
            municipios[9] = "Ixchiguán";
            municipios[10] = "Malacatán";
            municipios[11] = "Nuevo Progreso";
            municipios[12] = "Ocós";
            municipios[13] = "Pajapita";
            municipios[14] = "Esquipulas Palo Gordo";
            municipios[15] = "San Antonio Sacatepéquez";
            municipios[16] = "San Cristóbal Cucho";
            municipios[17] = "San José Ojetenam";
            municipios[18] = "San Lorenzo";
            municipios[19] = "San Miguel Ixtahuacán";
            municipios[20] = "San Pablo";
            municipios[21] = "San Pedro Sacatepéquez";
            municipios[22] = "San Rafael Pie de La Cuesta";
            municipios[23] = "Sipacapa";
            municipios[24] = "San Sebastián";
            municipios[25] = "Tacaná";
            municipios[26] = "Tajumulco";
            municipios[27] = "Tejutla";
            municipios[28] = "Río Blanco";
            municipios[29] = "La Blanca";

            ComboMunD.setEnabled(true);
        }
        return municipios;    //cbpaises es el nombre de su combo princioal
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboMunD;
    private javax.swing.JCheckBox checkEspecial;
    private javax.swing.JCheckBox checkEstandar;
    private javax.swing.JComboBox<String> comboDepD;
    private javax.swing.JComboBox<String> comboDepO;
    private javax.swing.JComboBox<String> comboMunO;
    private javax.swing.JLabel cotizacionT;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField librasT;
    private javax.swing.JTextField numPaquete;
    private javax.swing.JLabel precioEspecialT;
    private javax.swing.JLabel servicioEstandarT;
    // End of variables declaration//GEN-END:variables
}
