/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Objeto.Paneles;

import Objetos.Kioskos;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author 50232
 */

public class IngresoKiosko extends javax.swing.JPanel {


    /**
     * Creates new form IngresoKiosko
     */
    public IngresoKiosko() {
        initComponents();
           

    }
    
    public void cambiarcodigo(String codigo){
    codigokioskoT.setText("");
        codigokioskoT.setText(codigo);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nombrekioskoT = new javax.swing.JTextField();
        Bagregarkiosko = new javax.swing.JButton();
        codigokioskoT = new javax.swing.JTextField();
        regionC = new javax.swing.JComboBox<>();

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Codigo de Kiosko");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre kiosko");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Codigo de la region");

        nombrekioskoT.setBackground(new java.awt.Color(255, 255, 255));
        nombrekioskoT.setForeground(new java.awt.Color(0, 0, 0));

        Bagregarkiosko.setBackground(new java.awt.Color(0, 0, 0));
        Bagregarkiosko.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Bagregarkiosko.setForeground(new java.awt.Color(255, 255, 255));
        Bagregarkiosko.setText("Agregar Kiosko");
        Bagregarkiosko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BagregarkioskoActionPerformed(evt);
            }
        });

        codigokioskoT.setBackground(new java.awt.Color(255, 255, 255));
        codigokioskoT.setForeground(new java.awt.Color(0, 0, 0));
        codigokioskoT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigokioskoTActionPerformed(evt);
            }
        });

        regionC.setBackground(new java.awt.Color(255, 255, 255));
        regionC.setForeground(new java.awt.Color(0, 0, 0));
        regionC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Metropolitana", "Norte", "NororientSuroriente", "Suroccidente", "Noroccidente" }));
        regionC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regionCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Bagregarkiosko)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(regionC, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                            .addComponent(nombrekioskoT, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(codigokioskoT))))
                .addContainerGap(319, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(codigokioskoT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nombrekioskoT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(regionC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(Bagregarkiosko)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BagregarkioskoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BagregarkioskoActionPerformed
        // TODO add your handling code here:
        
     
     if(codigokioskoT.getText().isEmpty()||nombrekioskoT.getText().isEmpty()){
     JOptionPane.showMessageDialog(this, "Porfavor llene todos los campos");
     }
     else{
        listakiosko.add(new Kioskos(codigokioskoT.getText(),nombrekioskoT.getText(),regionC.getSelectedItem().toString()));
        codigokioskoT.setText("");
        nombrekioskoT.setText("");
        
     
    }   
    }//GEN-LAST:event_BagregarkioskoActionPerformed

    private void regionCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regionCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regionCActionPerformed

    private void codigokioskoTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigokioskoTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigokioskoTActionPerformed

    ArrayList  <Kioskos> listakiosko =new ArrayList<Kioskos>();
    
    public ArrayList<Kioskos> getListakiosko(){
       return listakiosko;
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bagregarkiosko;
    private javax.swing.JTextField codigokioskoT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombrekioskoT;
    private javax.swing.JComboBox<String> regionC;
    // End of variables declaration//GEN-END:variables
}
