/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Objeto.Paneles;

import Objetos.Tarjeta;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author 50232
 */
public class RegistoTarjeta extends javax.swing.JPanel {

    /**
     * Creates new form RegistoTarjeta
     */
    public RegistoTarjeta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nombreTarjetaT = new javax.swing.JTextField();
        fechaTarjetaT = new javax.swing.JTextField();
        numeroTarjetaT = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre de la Tarjeta:");

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fecha de Vencimiento:");

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Numero de la Tarjeta:");

        nombreTarjetaT.setBackground(new java.awt.Color(255, 255, 255));
        nombreTarjetaT.setForeground(new java.awt.Color(0, 0, 0));

        fechaTarjetaT.setBackground(new java.awt.Color(255, 255, 255));
        fechaTarjetaT.setForeground(new java.awt.Color(0, 0, 0));

        numeroTarjetaT.setBackground(new java.awt.Color(255, 255, 255));
        numeroTarjetaT.setForeground(new java.awt.Color(0, 0, 0));
        numeroTarjetaT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroTarjetaTActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 153));
        jButton1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Agregar Tarjeta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fechaTarjetaT, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numeroTarjetaT, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombreTarjetaT, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jButton1)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nombreTarjetaT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(numeroTarjetaT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fechaTarjetaT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(73, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void numeroTarjetaTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroTarjetaTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroTarjetaTActionPerformed

        public void setListadeTarjeta(ArrayList <Tarjeta> listaProductos){
        this.listaTarjeta=listaProductos;
    }

    
    public ArrayList<Tarjeta> getListaTarjeta() {
        return listaTarjeta;
    }
        
    ArrayList<Tarjeta> listaTarjeta=new ArrayList();
    

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       /*
        String mandarTarjeta="XXXX-XXXX-XXXX-"+numeroTarjetaT.getText().substring(12);
       varPago.ComboTarjeta.addItem(mandarTarjeta);
        */
        if(nombreTarjetaT.getText().isEmpty()||numeroTarjetaT.getText().isEmpty()||fechaTarjetaT.getText().isEmpty()){
     JOptionPane.showMessageDialog(this, "Porfavor llene todos los campos");
     }
       
        else if(numeroTarjetaT.getText().length() == 16){
      //El arraylist listaTarjeta lo declate dentro de este panel, pero que funciona con la clase de IngresoUsuarios.
      
         if(numeroTarjetaT.getText().matches("[0-9]+")){
         listaTarjeta.add(new Tarjeta(numeroTarjetaT.getText()));
        nombreTarjetaT.setText("");
        numeroTarjetaT.setText("");
        fechaTarjetaT.setText("");
         }else{JOptionPane.showMessageDialog(null, "El numero de Tarjeta debe contener solamente numeros ");}
        
      
    } else{
            JOptionPane.showMessageDialog(this, "El numero de Tarjeta debe tener 16 caracteres");
        }
        
               
    }//GEN-LAST:event_jButton1ActionPerformed
 //Metodo para minusculas 
    public static boolean numeros(String numT){
     for(int i=0;i<numT.length();i++){
         if(Character.isDigit(numT.charAt(i)))
             return true;
     }
     return false;
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fechaTarjetaT;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField nombreTarjetaT;
    private javax.swing.JTextField numeroTarjetaT;
    // End of variables declaration//GEN-END:variables
}
