/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Objeto.Paneles;

import Objetos.datoFactura;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author 50232
 */
public class RegistroDatosFacturacion extends javax.swing.JPanel {

    /**
     * Creates new form RegistroDatosFacturacion
     */
    public RegistroDatosFacturacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nombreFacturaT = new javax.swing.JTextField();
        nitFacturaT = new javax.swing.JTextField();
        direccionFacturaT = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Dirección:");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre Completo:");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NIT:");

        nombreFacturaT.setBackground(new java.awt.Color(255, 255, 255));
        nombreFacturaT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nombreFacturaT.setForeground(new java.awt.Color(0, 0, 0));
        nombreFacturaT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreFacturaTActionPerformed(evt);
            }
        });

        nitFacturaT.setBackground(new java.awt.Color(255, 255, 255));
        nitFacturaT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nitFacturaT.setForeground(new java.awt.Color(0, 0, 0));
        nitFacturaT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nitFacturaTActionPerformed(evt);
            }
        });

        direccionFacturaT.setBackground(new java.awt.Color(255, 255, 255));
        direccionFacturaT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        direccionFacturaT.setForeground(new java.awt.Color(0, 0, 0));
        direccionFacturaT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direccionFacturaTActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Registrar Datos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Modificar nombre");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Modificar Direccion");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setForeground(new java.awt.Color(0, 0, 0));
        jButton7.setText("Modificar Nit");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreFacturaT, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(direccionFacturaT, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nitFacturaT, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jButton2)
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton7)))))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nombreFacturaT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(direccionFacturaT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nitFacturaT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3)
                        .addComponent(jButton7)))
                .addGap(27, 27, 27)
                .addComponent(jButton1)
                .addContainerGap(39, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nombreFacturaTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreFacturaTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreFacturaTActionPerformed

    private void nitFacturaTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nitFacturaTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nitFacturaTActionPerformed

    private void direccionFacturaTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direccionFacturaTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_direccionFacturaTActionPerformed

String nombreguardado="In Nombre";
String direccionguardada="In Direccion";
String nitguardado="In Nit";
String nitfacturaTempo="";

    public String getNitfactura() {
        return nitfacturaTempo;
    }

    public void setNitfactura(String nitfactura) {
        this.nitfacturaTempo = nitfactura;
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       if(nitFacturaT.getText().matches("[0-9]+")){
       nombreguardado=nombreFacturaT.getText();
        direccionguardada=direccionFacturaT.getText();
        nitfacturaTempo=nitFacturaT.getText();
        nitguardado=nitFacturaT.getText(); 
        System.out.println("-Imprimo la variable NombreGuardado---"+nombreguardado);
     //   nombreFacturaT.setEnabled(false);
        nombreFacturaT.setEnabled(false);
        direccionFacturaT.setEnabled(false);
        nitFacturaT.setEnabled(false);
        DF.setNombreF(nombreFacturaT.getText());
        System.out.println("variable de la clase "+DF.getNombreF());
        
        datoF.add(new datoFactura(nombreguardado,direccionguardada,nitguardado));
       }else{JOptionPane.showMessageDialog(null, "En el nit solo pueden haber numeros, intente de nuevo porfavor. ");}
        
    }//GEN-LAST:event_jButton1ActionPerformed
 //Metodo para minusculas 
    public static boolean numeros(String numN){
     for(int i=0;i<numN.length();i++){
         if(Character.isDigit(numN.charAt(i)))
             return true;
     }
     return false;
  }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        nombreFacturaT.setEnabled(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        direccionFacturaT.setEnabled(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        nitFacturaT.setEnabled(true);
    }//GEN-LAST:event_jButton7ActionPerformed
  
    ArrayList<datoFactura> datoF=new ArrayList<datoFactura>();

    datoFactura DF=new datoFactura();
    
    public ArrayList<datoFactura> getDatoF() {
        return datoF;
    }

    
    public String getnombreFact() {
        return nombreguardado;
    }
    public String getdireccionFact(){
        return direccionguardada;
    }
    
    public String getnitFact(){
        return nitguardado;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField direccionFacturaT;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField nitFacturaT;
    private javax.swing.JTextField nombreFacturaT;
    // End of variables declaration//GEN-END:variables
}
